import { StyleSheet, View } from 'react-native';

import {
  AppText,
  Button,
  Card,
  colors,
  spacing,
} from '../ui';

import { useGithubConnection } from './GithubConnectionProvider';

/*
 * The GitHub section of the Profile screen.
 *
 * Deliberately plain: it reuses Card, AppText and Button exactly as the
 * rest of Profile does, and adds no new visual language. This phase is
 * integration, not design.
 *
 * The copy is the part worth attention. Everything here describes what
 * Career OS READS, never what it concludes. "Public repository activity"
 * is a fact about the data; "we understand your skills" would be a claim
 * about the person, and GitHub cannot support one. The same restraint
 * applies to the sync summary, which is generated by describeSyncSummary
 * and never rounds a partial result up to a complete one.
 */
export function GithubConnectionCard() {
  const {
    state,
    status,
    message,
    connect,
    sync,
    disconnect,
  } = useGithubConnection();

  const busy =
    state === 'connecting' ||
    state === 'syncing';

  /*
   * Read from the derived state, not from status.connected. The API
   * reports connected: true whenever a connection row exists and carries
   * the row's real state separately, so a REVOKED or INVALID connection
   * would otherwise render a Sync button that the server refuses with a
   * 404. deriveUiState requires ACTIVE.
   */
  const connected =
    state === 'connected' ||
    state === 'partial' ||
    state === 'syncing';

  return (
    <View style={styles.section}>
      <AppText variant="heading">
        Connected accounts
      </AppText>

      <Card>
        <View style={styles.rows}>
          <View style={styles.header}>
            <AppText variant="bodyMedium">
              GitHub
            </AppText>

            <AppText
              variant="caption"
              muted
            >
              {connected
                ? statusLabel(state)
                : state === 'error'
                  ? 'Status unavailable'
                  : 'Not connected'}
            </AppText>
          </View>

          {connected ? (
            <ConnectedDetail
              login={status?.login ?? null}
              lastSyncedAt={
                status?.lastSyncedAt ?? null
              }
            />
          ) : state === 'error' ? null : (
            <AppText variant="caption" muted>
              Connecting GitHub lets Career OS read
              your public repository activity and
              record it as evidence in your career
              graph. It never reads private
              repositories and never writes
              anything to GitHub.
            </AppText>
          )}

          {message ? (
            <AppText
              variant="caption"
              style={
                state === 'error'
                  ? styles.error
                  : styles.note
              }
            >
              {message}
            </AppText>
          ) : null}

          <View style={styles.actions}>
            {state === 'error' ? (
              /*
               * A failed status read is not a disconnection. Offering
               * "Connect GitHub" here would invite a user with a healthy
               * connection to start a second OAuth flow on the strength of
               * one dropped request - so nothing is offered until we know.
               */
              null
            ) : connected ? (
              <>
                <Button
                  title={
                    state === 'syncing'
                      ? 'Syncing…'
                      : 'Sync GitHub'
                  }
                  onPress={() => void sync()}
                  /*
                   * Disabled while anything is in flight, so a second tap
                   * cannot start a second run. The provider guards this
                   * again with a ref, because a disabled prop is a render
                   * behind the tap that caused it.
                   */
                  disabled={busy}
                />

                <Button
                  title="Disconnect"
                  onPress={() =>
                    void disconnect()
                  }
                  disabled={busy}
                />
              </>
            ) : (
              <Button
                title={
                  state === 'connecting'
                    ? 'Opening GitHub…'
                    : 'Connect GitHub'
                }
                onPress={() => void connect()}
                disabled={busy}
              />
            )}
          </View>
        </View>
      </Card>
    </View>
  );
}

function ConnectedDetail({
  login,
  lastSyncedAt,
}: {
  login: string | null;
  lastSyncedAt: string | null;
}) {
  return (
    <View style={styles.detail}>
      {/*
       * The login only. Not the numeric account id, not the granted
       * scopes, not any token metadata - none of which a person needs in
       * order to know which account is attached.
       */}
      {login ? (
        <AppText variant="caption" muted>
          Connected as @{login}
        </AppText>
      ) : null}

      <AppText variant="caption" muted>
        {lastSyncedAt
          ? `Last sync finished ${formatDate(lastSyncedAt)}`
          : 'Not synced yet'}
      </AppText>
    </View>
  );
}

/*
 * "A sync run finished", which is what the server records - not "your
 * GitHub data is current as of this moment". A partial run stamps this
 * too, and describing it as freshness would overstate what happened.
 */
function formatDate(value: string): string {
  const parsed = Date.parse(value);

  if (Number.isNaN(parsed)) {
    return 'recently';
  }

  return new Date(parsed).toLocaleDateString();
}

function statusLabel(
  state: string,
): string {
  if (state === 'syncing') {
    return 'Syncing…';
  }

  if (state === 'partial') {
    return 'Connected · partly updated';
  }

  return 'Connected';
}

const styles = StyleSheet.create({
  section: {
    gap: spacing.sm,
  },
  rows: {
    gap: spacing.sm,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  detail: {
    gap: spacing.xs,
  },
  actions: {
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  note: {
    color: colors.textSecondary,
  },
  error: {
    color: colors.danger,
  },
});
